---
# These tasks require the use of escalated privileges, which are stored using
# ansible-vault under the `../host_vars/[hostname]/secret.yaml'
- name: Install essential packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Disable SSH empty password auth
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitEmptyPasswords no"
    line: "PermitEmptyPasswords no"
  register: sshd_config

- name: Restart SSH daemon
  become: true
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

