---
- name: Update package repository (equivalent to "apt-get upgrade")
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify: "restart server"
