---
- name: Rebooting server
  ansible.builtin.reboot:
  notify: "start mc server"
  listen: "restart server"

- name: Start Minecraft Server
  ansible.builtin.shell:
    cmd: nohup ./start_server.sh &
    args:
      chdir: minecraft_server
  listen: "start mc server"
